/*
 * //==============================================================//
 * // by lukman
 * //==============================================================//
 */
package menu;

import utility.Koneksi;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author lukman
 */
public class BahanForm extends javax.swing.JInternalFrame {
    int idBahan, w, h, mode;
    JDesktopPane desktop;
    String QUERY_CODE, QUERY_SAVE;

    /**
     * Creates new form BahanForm
     */
    public BahanForm() {
        initComponents();
    }
    
    public void setDeskop(JDesktopPane desktop, int w, int h){
        this.desktop = desktop;
        this.w = w;
        this.h = h;
    }
    
    public void setField(String mode, int id){   
        switch (mode){
            case "ADD" :
                try{
                    Connection c = Koneksi.configDB();
                    Statement s = c.createStatement();
                    ResultSet rs=s.executeQuery(QUERY_CODE);
                    if(rs.first()==false){
                        idKainField.setText("1");
                    }else{
                        rs.last();
                        int no=rs.getInt(1)+1;
                        String idNumb = Integer.toString(no);
                        idKainField.setText(idNumb);
                    }
                }catch(SQLException e){
                    System.out.println("Error :" +e.getMessage());
                }
            break;
            case "EDIT" :
                try{
                    Connection Conn = (Connection) Koneksi.configDB();
                    Statement st = Conn.createStatement();
                    ResultSet res = st.executeQuery(QUERY_CODE);
                    while(res.next()){
                        idKainField.setText(res.getString(1));
                        nameKainField.setText(res.getString(2));
                        typeKainField.setText(res.getString(3));
                        colorKainField.setText(res.getString(4));
                    }
                }catch (SQLException e){
                    System.out.println(e.getMessage());
                }
            break;
        }        
    }
    
    public void setMode(String mode, int id){
        switch (mode){
            case "ADD" :
                setTitle("ADD BAHAN BAKU KAIN");
                QUERY_CODE = "SELECT id_kain FROM bahanbaku_kain ORDER BY id_kain ASC";
                setField(mode, id);
                this.mode = 0;
            break;
            case "EDIT" :
                idKainField.setEnabled(false);
                setTitle("EDIT BAHAN BAKU KAIN");
                QUERY_CODE = "SELECT * FROM bahanbaku_kain WHERE id_kain = '"+id+"'";
                setField(mode, id);
                this.mode = 1;
            break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idKainField = new javax.swing.JTextField();
        nameKainField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        typeKainField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        colorKainField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        jLabel1.setText("id");

        jLabel2.setText("Nama Bahan");

        nameKainField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameKainFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis Bahan");

        jLabel4.setText("Warna");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel5.setText("*gunakan koma (,)  jika varian warna lebih dari 1");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel6.setText("Ex :  Merah,Kuning,Hijau");

        jLabel7.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabel7.setText("// editing id isn't recomended");

        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("CANCEL");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(typeKainField)
                            .addComponent(colorKainField)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel6))
                                    .addComponent(idKainField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addComponent(nameKainField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idKainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameKainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(typeKainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(colorKainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameKainFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameKainFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameKainFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    String id, name, type, color;
    id = idKainField.getText();
    name = nameKainField.getText();
    type = typeKainField.getText();
    color = colorKainField.getText();
    
    if (idKainField.getText().isEmpty() || nameKainField.getText().isEmpty() || typeKainField.getText().isEmpty() 
            || colorKainField.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Field tidak boleh kosong");
    }else{
        try{     
            if ( mode == 0){
                QUERY_SAVE = "INSERT INTO `bahanbaku_kain` (`id_kain`, `name`, `type`, `color`) "
                        + "VALUES ('"+id+"', '"+name+"', '"+type+"', '"+color+"')";
            } else {
                QUERY_SAVE = "UPDATE `bahanbaku_kain` SET "
                    + "`name` = '"+name+"' , "
                    + "`type` = '"+type+"', "
                    + "`color` = '"+color+"' "
                    + "WHERE `bahanbaku_kain`.`id_kain` = "+id;
            }

            Connection Conn = (Connection) Koneksi.configDB();
            PreparedStatement sql = Conn.prepareStatement(QUERY_SAVE);
            sql.execute();
            JOptionPane.showMessageDialog(null, "SUKSES");
            this.dispose();
            Bahan p= new Bahan();
            desktop.add(p);
            p.setDeskop(desktop, w, h);
            p.setLocation((w - p.getSize().width)/2, (h-p.getSize().height)/2);
            p.toFront();
            p.setVisible(true);
            this.dispose();            
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
        Bahan p= new Bahan();
        desktop.add(p);
        p.setDeskop(desktop, w, h);
        p.setLocation((w - p.getSize().width)/2, (h-p.getSize().height)/2);
        p.toFront();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField colorKainField;
    private javax.swing.JTextField idKainField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameKainField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField typeKainField;
    // End of variables declaration//GEN-END:variables


}
