/*
 * //==============================================================//
 * // by lukman                                                     //
 * //==============================================================//
 */
package menu;


import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import utility.Koneksi;

/**
 *
 * @author lukman
 */
public class ProdukForm extends javax.swing.JInternalFrame {
    int idProduk, w, h, mode;
    JDesktopPane desktop;
    String QUERY_CODE, QUERY_SAVE;
    

    /**
     * Creates new form ProdukForm
     */
    public ProdukForm() {
        initComponents();
    }
    
    public void setDeskop(JDesktopPane desktop, int w, int h){
        this.desktop = desktop;
        this.w = w;
        this.h = h;
    }
    
    public void setMode(String mode, int id){
        switch (mode){
            case "ADD" :
                setTitle("ADD PRODUK");
                QUERY_CODE = "SELECT id_produk FROM produk ORDER BY id_produk ASC";
                setField(mode, id);
                this.mode = 0;
                break;
            case "EDIT" :
                idProdukField.setEnabled(false);
                setTitle("EDIT PRODUK");
                QUERY_CODE = "SELECT * FROM produk WHERE id_produk = '"+id+"'";
                setField(mode, id);
                this.mode = 1;
                break;
        }
    }
    
    public void setField(String mode, int id){   
        switch (mode){
            case "ADD" :
                try{
                    Connection c = Koneksi.configDB();
                    Statement s = c.createStatement();
                    ResultSet rs=s.executeQuery(QUERY_CODE);
                    if(rs.first()==false){
                        idProdukField.setText("1");
                    }else{
                        rs.last();
                        int no=rs.getInt(1)+1;
                        String idNumb = Integer.toString(no);
                        idProdukField.setText(idNumb);
                    }
                }catch(SQLException e){
                    System.out.println("Error: " +e.getMessage());
                }
            break;
            case "EDIT" :
                try{
                    Connection Conn = (Connection) Koneksi.configDB();
                    Statement st = Conn.createStatement();
                    ResultSet res = st.executeQuery(QUERY_CODE);
                    while(res.next()){
                        idProdukField.setText(res.getString(1));
                        nameProdukField.setText(res.getString(2));
                    }
                }catch (SQLException e){
                    System.out.println("Error: "+e.getMessage());
                }
            break;
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idProdukField = new javax.swing.JTextField();
        nameProdukField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        jLabel1.setText("id");

        jLabel2.setText("Jenis Kerudung");

        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("CANCEL");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idProdukField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameProdukField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idProdukField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameProdukField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String id = idProdukField.getText();
        String name = nameProdukField.getText();
        
        if(id.equals("") || name.equals("")){
            JOptionPane.showMessageDialog(null, "Field tidak boleh kosong");
        }else{
            try{     
                if ( mode == 0){
                    QUERY_SAVE = "INSERT INTO `produk` (`id_produk`, `name`) "
                        + "VALUES ('"+id+"', '"+name+"')";
                } else {
                    QUERY_SAVE = "UPDATE `produk` SET `name` = '"+name+"' WHERE `produk`.`id_produk` = '"+id+"'";
                }

                Connection Conn = (Connection) Koneksi.configDB();
                PreparedStatement sql = Conn.prepareStatement(QUERY_SAVE);
                sql.execute();
                JOptionPane.showMessageDialog(null, "SUKSES");
                this.dispose();
                Produk p= new Produk();
                desktop.add(p);
                p.setDeskop(desktop, w, h);
                p.setLocation((w - p.getSize().width)/2, (h-p.getSize().height)/2);
                p.toFront();
                p.setVisible(true);
                this.dispose();            
            }catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
        Produk p= new Produk();
        desktop.add(p);
        p.setDeskop(desktop, w, h);
        p.setLocation((w - p.getSize().width)/2, (h-p.getSize().height)/2);
        p.toFront();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField idProdukField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nameProdukField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
